spring:
  application:
    name: wanlv-back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wanlv?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

server:
  port: 8080
  servlet:
    context-path: /

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.wanlvback.pojo.entity,com.example.wanlvback.pojo.dto,com.example.wanlvback.pojo.vo
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: 'NULL'

logging:
  level:
    com.example.wanlvback.mapper: debug

